services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: propertyhub_dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONUNBUFFERED=1
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/app
      - /app/.venv
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
